# Generated by Django 3.2 on 2021-06-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210610_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='payments.payment'),
        ),
    ]
