# Generated by Django 3.2 on 2021-06-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_user'),
        ('payments', '0004_auto_20210614_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_detail', to='orders.orders'),
        ),
    ]
