OPEN = "Abierto"
PENDING_PAYMENT = "Pago pendiente"
PENDING_SHIPPING = "Envio pendiente"
SHIPPED = "Enviado"
DELIVERED = "Entregado"
STATUS = (
    (OPEN, OPEN),
    (PENDING_PAYMENT, PENDING_PAYMENT),
    (PENDING_SHIPPING, PENDING_SHIPPING),
    (SHIPPED, SHIPPED),
    (DELIVERED, DELIVERED)
)
