# Generated by Django 3.2 on 2022-03-15 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=100)),
                ('cellphone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Envio pendiente', 'Envio pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envioss',
            },
        ),
        migrations.CreateModel(
            name='ProductsToShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delete_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True)),
                ('product_to_send', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderproductdetail')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_ship', to='shipments.shipments')),
            ],
            options={
                'verbose_name': 'Producto para enviar',
                'verbose_name_plural': 'Productos para enviar',
                'unique_together': {('shipment', 'product_to_send')},
            },
        ),
    ]
