# Generated by Django 3.2 on 2021-06-14 02:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210610_2352'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='cellphone_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.CreateModel(
            name='ProductsToShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_to_send', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderproductdetail')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_to_ship', to='shipments.shipments')),
            ],
            options={
                'db_table': 'products_to_ship',
                'unique_together': {('shipment', 'product_to_send')},
            },
        ),
    ]
