# Generated by Django 3.2 on 2021-06-14 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_user'),
        ('shipments', '0002_auto_20210614_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.orders'),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('PENDING_SHIPPING', 'PENDING_SHIPPING'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], max_length=30),
        ),
    ]
