# Generated by Django 3.2 on 2021-06-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20210614_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='cellphone_number',
            field=models.CharField(max_length=20),
        ),
    ]
