# Generated by Django 3.2 on 2022-03-14 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstoship',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productstoship',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipments',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productstoship',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shipments',
            name='status',
            field=models.CharField(choices=[('Envio pendiente', 'Envio pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], max_length=30),
        ),
    ]
