# Generated by Django 3.2 on 2021-06-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_availableproducts_product'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='orderproductdetail',
            unique_together={('order', 'product')},
        ),
    ]
