# Generated by Django 3.2 on 2021-06-10 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210610_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproductdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='orders.orders'),
        ),
    ]
