# Generated by Django 3.2 on 2022-03-14 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductdetail',
            options={'verbose_name': 'Detalle orden producto', 'verbose_name_plural': 'Detalles ordenes productos'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AddField(
            model_name='orderproductdetail',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderproductdetail',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderproductdetail',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Pago pendiente', 'Pago pendiente'), ('Envio pendiente', 'Envio pendiente'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], max_length=30),
        ),
        migrations.AlterModelTable(
            name='orderproductdetail',
            table=None,
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
    ]
