# Generated by Django 4.0.3 on 2022-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_availableproducts_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableproducts',
            options={'verbose_name': 'Unidad disponible', 'verbose_name_plural': 'Unidades disponibles'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='availableproducts',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='delete_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='products',
            name='unit_price',
            field=models.FloatField(verbose_name='Precio por unidad'),
        ),
        migrations.AlterModelTable(
            name='availableproducts',
            table=None,
        ),
        migrations.AlterModelTable(
            name='products',
            table=None,
        ),
    ]
