# Generated by Django 3.2 on 2022-03-14 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_availableproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableproducts',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='availableproducts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
